const rooms = [
    {
        id: 1,
        title: "Phòng trọ cao cấp gần Đại học Bách Khoa",
        location: "Hai Bà Trưng, Hà Nội",
        price: "4.500.000",
        unit: "₫",
        area: "25m²",
        features: ["WiFi miễn phí", "Điều hòa", "Tủ lạnh", "Máy giặt", "Tủ quần áo", "Ban công"],
        host: { name: "Chị Lan Anh", avatar: "https://storage.googleapis.com/a1aa/image/e281b100-dae6-48ab-2398-9b530ff6f63c.jpg" },
        img: "https://storage.googleapis.com/a1aa/image/93a724c2-0f7f-48d4-31c6-b4460d154652.jpg",
        status: "Còn trống",
        statusColor: "badge-success",
        alt: "Phòng cao cấp có sofa, bàn trà, tranh treo tường, cửa kính lớn nhìn ra thành phố",
    },
    {
        id: 2,
        title: "Studio hiện đại tại Cầu Giấy",
        location: "Cầu Giấy, Hà Nội",
        price: "6.800.000",
        unit: "₫",
        area: "35m²",
        features: ["WiFi miễn phí", "Điều hòa", "Tủ lạnh", "Bếp riêng", "Máy giặt", "Tủ quần áo"],
        host: { name: "Anh Minh Tuấn", avatar: "https://storage.googleapis.com/a1aa/image/86a7d16c-3cf2-4702-3cbe-6b71bf7dba0e.jpg" },
        img: "https://storage.googleapis.com/a1aa/image/773371be-f373-4d51-1875-b8a8355365c4.jpg",
        status: "Còn trống",
        statusColor: "badge-success",
        alt: "Studio hiện đại với bếp và cửa kính lớn nhìn ra ban công",
    },
    {
        id: 3,
        title: "Phòng chia sẻ giá rẻ tại Đống Đa",
        location: "Đống Đa, Hà Nội",
        price: "2.200.000",
        unit: "₫",
        area: "20m²",
        features: ["WiFi miễn phí", "Điều hòa", "Tủ lạnh", "Nhà bếp chung", "Phòng tắm chung"],
        host: { name: "Cô Hương", avatar: "https://storage.googleapis.com/a1aa/image/7e127ebd-470a-465e-a963-8ab530fb03bd.jpg" },
        img: "https://storage.googleapis.com/a1aa/image/a7c00a23-8392-4f34-65b7-60efc44e824b.jpg",
        status: "Còn trống",
        statusColor: "badge-success",
        alt: "Phòng ngủ có giường đôi, cửa sổ lớn, ánh sáng vàng ấm áp",
    },
    {
        id: 4,
        title: "Căn hộ mini 1 phòng ngủ tại Thanh Xuân",
        location: "Thanh Xuân, Hà Nội",
        price: "8.500.000",
        unit: "₫",
        area: "45m²",
        features: ["WiFi miễn phí", "Điều hòa", "Tủ lạnh", "Bếp riêng", "Máy giặt", "Tủ quần áo", "Ban công"],
        host: { name: "Anh Đức", avatar: "https://storage.googleapis.com/a1aa/image/756cb5b0-92f3-4c0b-9a9f-0e4f70707187.jpg" },
        img: "https://storage.googleapis.com/a1aa/image/35b313ab-6cc8-4c38-a36f-2c35bdc4bd9b.jpg",
        status: "Đã thuê",
        statusColor: "badge-danger",
        alt: "Căn hộ mini 1 phòng ngủ có kệ sách, cửa sổ lớn ánh sáng tự nhiên",
    },
    {
        id: 5,
        title: "Phòng trọ gần Metro Cát Linh - Hà Đông",
        location: "Hà Đông, Hà Nội",
        price: "3.800.000",
        unit: "₫",
        area: "22m²",
        features: ["WiFi miễn phí", "Điều hòa", "Tủ lạnh", "Máy giặt", "Tủ quần áo", "Gần Metro"],
        host: { name: "Chị Mai", avatar: "https://storage.googleapis.com/a1aa/image/4ef149cd-a2a3-49f8-7d0d-cb538ccdcf6e.jpg" },
        img: "https://storage.googleapis.com/a1aa/image/cbb6d23e-35ef-442b-2bbb-28597a2565df.jpg",
        status: "Còn trống",
        statusColor: "badge-success",
        alt: "Phòng trọ có ghế sofa, bàn trà, cửa sổ lớn ánh sáng tự nhiên",
    },
];

const testimonials = [
    {
        id: 1,
        name: "Nguyễn Văn An",
        role: "Sinh viên tại Hà Nội",
        avatar: "https://storage.googleapis.com/a1aa/image/3c79f507-b77e-446d-f21a-ea686c49e64d.jpg",
        rating: 5,
        text:
            "Tôi đã tìm được phòng trọ hoàn hảo qua RoomFinder. Giao diện dễ sử dụng và thông tin rất chi tiết!",
    },
    {
        id: 2,
        name: "Trần Thị Bình",
        role: "Nhân viên văn phòng",
        avatar: "https://storage.googleapis.com/a1aa/image/fbd18870-1388-421e-c456-409614202fc5.jpg",
        rating: 4.5,
        text:
            "Dịch vụ tuyệt vời! Tôi đã thuê được studio gần công ty chỉ trong 2 ngày. Rất hài lòng!",
    },
    {
        id: 3,
        name: "Lê Minh Tuấn",
        role: "Chủ trọ tại Cầu Giấy",
        avatar: "https://storage.googleapis.com/a1aa/image/1982233f-c595-49a7-78dc-0fd45aeff347.jpg",
        rating: 5,
        text:
            "Là chủ trọ, tôi thấy nền tảng này giúp kết nối được khách thuê uy tín một cách nhanh chóng.",
    },
];

export { rooms, testimonials };