const rooms = [
    {
        id: 1,
        title: "Phòng trọ cao cấp gần Đại học Bách Khoa",
        address: "123 Trần Đại Nghĩa, Hai Bà Trưng, Hà Nội",
        latitude: 21.004674,
        longitude: 105.846962,
        price: 4500000,
        area: 25,
        host: { name: "Chị Lan Anh", avatar: "https://storage.googleapis.com/a1aa/image/e281b100-dae6-48ab-2398-9b530ff6f63c.jpg" },
        images: [
            "https://storage.googleapis.com/a1aa/image/93a724c2-0f7f-48d4-31c6-b4460d154652.jpg",
            "https://storage.googleapis.com/a1aa/image/35b313ab-6cc8-4c38-a36f-2c35bdc4bd9b.jpg",
            "https://storage.googleapis.com/a1aa/image/a7c00a23-8392-4f34-65b7-60efc44e824b.jpg",
        ],
        status: "Còn trống",
        statusColor: "badge-success",
        description: "Phòng cao cấp đầy đủ nội thất, gần trường và tiện ích xung quanh.",
        properties: {
            HasAirConditioner: true,
            HasWifi: true,
            bedCount: 1,
            HasCloset: true,
            HasFridge: true,
            HasHotWater: true,
            HasWindow: true,
            note: "Ban công hướng Nam, thoáng mát",
        },
        reviews: [
            { id: 1, user: "Minh", rating: 5, comment: "Chủ nhà thân thiện, phòng sạch." },
            { id: 2, user: "Lan", rating: 4, comment: "Gần trường, giá hợp lý." },
        ],
        alt: "Phòng cao cấp có sofa, bàn trà, tranh treo tường, cửa kính lớn nhìn ra thành phố",
    },
    {
        id: 2,
        title: "Studio hiện đại tại Cầu Giấy",
        address: "56 Nguyễn Phong Sắc, Cầu Giấy, Hà Nội",
        latitude: 21.040902,
        longitude: 105.789352,
        price: 6800000,
        area: 35,
        host: { name: "Anh Minh Tuấn", avatar: "https://storage.googleapis.com/a1aa/image/86a7d16c-3cf2-4702-3cbe-6b71bf7dba0e.jpg" },
        images: [
            "https://storage.googleapis.com/a1aa/image/773371be-f373-4d51-1875-b8a8355365c4.jpg",
            "https://storage.googleapis.com/a1aa/image/93a724c2-0f7f-48d4-31c6-b4460d154652.jpg",
        ],
        status: "Còn trống",
        statusColor: "badge-success",
        description: "Studio rộng rãi, ánh sáng tự nhiên, bếp riêng tiện nghi.",
        properties: {
            HasAirConditioner: true,
            HasWifi: true,
            bedCount: 1,
            HasCloset: true,
            HasFridge: true,
            HasHotWater: true,
            HasWindow: true,
            HasPet: true,
            note: null,
        },
        reviews: [
            { id: 1, user: "Hà", rating: 5, comment: "Studio đẹp, đầy đủ tiện nghi." },
            { id: 2, user: "Quang", rating: 4.5, comment: "Vị trí thuận tiện, chủ nhà nhiệt tình." },
        ],
        alt: "Studio hiện đại với bếp và cửa kính lớn nhìn ra ban công",
    },
    {
        id: 3,
        title: "Phòng chia sẻ giá rẻ tại Đống Đa",
        address: "12 Tôn Đức Thắng, Đống Đa, Hà Nội",
        latitude: 21.028511,
        longitude: 105.804817,
        price: 2200000,
        area: 20,
        features: ["WiFi miễn phí", "Điều hòa", "Tủ lạnh", "Nhà bếp chung", "Phòng tắm chung"],
        host: { name: "Cô Hương", avatar: "https://storage.googleapis.com/a1aa/image/7e127ebd-470a-465e-a963-8ab530fb03bd.jpg" },
        images: [
            "https://storage.googleapis.com/a1aa/image/a7c00a23-8392-4f34-65b7-60efc44e824b.jpg",
        ],
        status: "Còn trống",
        statusColor: "badge-success",
        description: "Phòng chia sẻ phù hợp sinh viên, tiết kiệm chi phí.",
        properties: {
            HasAirConditioner: true,
            HasWifi: true,
            bedCount: 1,
            HasCloset: false,
            HasFridge: true,
            HasHotWater: true,
            HasWindow: false,
            HasPet: false,
            Note: "Có giờ giấc chung",
        },
        reviews: [
            { id: 1, user: "Phương", rating: 4, comment: "Phòng sạch sẽ, giá rẻ." },
            { id: 2, user: "Tuấn", rating: 3.5, comment: "Phù hợp với sinh viên." },
        ],
        alt: "Phòng ngủ có giường đôi, cửa sổ lớn, ánh sáng vàng ấm áp",
    },
];

const testimonials = [
    {
        id: 1,
        name: "Nguyễn Văn An",
        role: "Sinh viên tại Hà Nội",
        avatar: "https://storage.googleapis.com/a1aa/image/3c79f507-b77e-446d-f21a-ea686c49e64d.jpg",
        rating: 5,
        text:
            "Tôi đã tìm được phòng trọ hoàn hảo qua RoomFinder. Giao diện dễ sử dụng và thông tin rất chi tiết!",
    },
    {
        id: 2,
        name: "Trần Thị Bình",
        role: "Nhân viên văn phòng",
        avatar: "https://storage.googleapis.com/a1aa/image/fbd18870-1388-421e-c456-409614202fc5.jpg",
        rating: 4.5,
        text:
            "Dịch vụ tuyệt vời! Tôi đã thuê được studio gần công ty chỉ trong 2 ngày. Rất hài lòng!",
    },
    {
        id: 3,
        name: "Lê Minh Tuấn",
        role: "Chủ trọ tại Cầu Giấy",
        avatar: "https://storage.googleapis.com/a1aa/image/1982233f-c595-49a7-78dc-0fd45aeff347.jpg",
        rating: 5,
        text:
            "Là chủ trọ, tôi thấy nền tảng này giúp kết nối được khách thuê uy tín một cách nhanh chóng.",
    },
];

export { rooms, testimonials };