// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251008060121_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApi.Domain.Entities.BoardingHouse", b =>
                {
                    b.Property<int>("House_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("House_Id"));

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Create_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Electric_Cost")
                        .HasColumnType("int");

                    b.Property<string>("House_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Is_Elevator")
                        .HasColumnType("bit");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("Water_Cost")
                        .HasColumnType("int");

                    b.HasKey("House_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("BoardingHouses");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Booking_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Check_In_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Check_Out_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("Room_Id1")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id1")
                        .HasColumnType("int");

                    b.HasKey("Booking_Id");

                    b.HasIndex("Room_Id1");

                    b.HasIndex("User_Id1");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.ChatConversation", b =>
                {
                    b.Property<int>("Conversation_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Conversation_Id"));

                    b.Property<int>("Host_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_Message_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Conversation_Id");

                    b.HasIndex("Host_Id");

                    b.HasIndex("Room_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("ChatConversations");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Message_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Message_Id"));

                    b.Property<int>("ChatConversationConversation_Id")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Conversation_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id1")
                        .HasColumnType("int");

                    b.HasKey("Message_Id");

                    b.HasIndex("ChatConversationConversation_Id");

                    b.HasIndex("User_Id1");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.CheckBooking", b =>
                {
                    b.Property<int>("Check_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Check_Id"));

                    b.Property<int>("Booking_Id")
                        .HasColumnType("int");

                    b.Property<int>("Booking_Id1")
                        .HasColumnType("int");

                    b.Property<int>("Check")
                        .HasColumnType("int");

                    b.Property<DateTime>("Check_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image_Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Check_Id");

                    b.HasIndex("Booking_Id1");

                    b.ToTable("CheckBookings");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.HouseImage", b =>
                {
                    b.Property<int>("House_Image_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("House_Image_Id"));

                    b.Property<int>("BoardingHouseHouse_Id")
                        .HasColumnType("int");

                    b.Property<int>("House_Id")
                        .HasColumnType("int");

                    b.Property<string>("Image_Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Uploaded_At")
                        .HasColumnType("datetime2");

                    b.HasKey("House_Image_Id");

                    b.HasIndex("BoardingHouseHouse_Id");

                    b.ToTable("HouseImages");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Notification_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Notification_Id"));

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_Read")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id1")
                        .HasColumnType("int");

                    b.HasKey("Notification_Id");

                    b.HasIndex("User_Id1");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("Booking_Id")
                        .HasColumnType("int");

                    b.Property<int>("Booking_Id1")
                        .HasColumnType("int");

                    b.Property<int>("Method_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Paid_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Transaction_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserPaymentMethodPayment_Method_Id")
                        .HasColumnType("int");

                    b.HasKey("Payment_Id");

                    b.HasIndex("Booking_Id1");

                    b.HasIndex("UserPaymentMethodPayment_Method_Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Report_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Report_Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reported_Id")
                        .HasColumnType("int");

                    b.Property<int>("ReporterUser_Id")
                        .HasColumnType("int");

                    b.Property<int>("Reporter_Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Report_Id");

                    b.HasIndex("ReporterUser_Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Room_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Room_Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("House_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Owner_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Room_Id");

                    b.HasIndex("House_Id");

                    b.HasIndex("Owner_Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.RoomImage", b =>
                {
                    b.Property<int>("Image_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Image_Id"));

                    b.Property<string>("Image_Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("Room_Id1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Uploaded_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Image_Id");

                    b.HasIndex("Room_Id1");

                    b.ToTable("RoomImages");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.RoomProperty", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<int>("BedCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasAirConditioner")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCloset")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PropertyId");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("RoomProperties");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("User_Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_Id = 1,
                            Email = "admin@gmail.com",
                            PasswordHash = "admin",
                            Role = 2,
                            User_Name = "admin"
                        },
                        new
                        {
                            User_Id = 2,
                            Email = "test@gmail.com",
                            PasswordHash = "123456",
                            Role = 0,
                            User_Name = "test"
                        },
                        new
                        {
                            User_Id = 3,
                            Email = "host@gmail.com",
                            PasswordHash = "123456",
                            Role = 1,
                            User_Name = "host test"
                        });
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserInfor", b =>
                {
                    b.Property<int>("Infor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Infor_Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("Update_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Infor_Id");

                    b.HasIndex("User_Id")
                        .IsUnique();

                    b.ToTable("UserInfors");

                    b.HasData(
                        new
                        {
                            Infor_Id = 1,
                            Phone = "0123456789",
                            User_Id = 1
                        },
                        new
                        {
                            Infor_Id = 2,
                            Phone = "0987654321",
                            User_Id = 2
                        });
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserPaymentMethod", b =>
                {
                    b.Property<int>("Payment_Method_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_Method_Id"));

                    b.Property<string>("Account_User_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bank_Account_Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bank_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Create_At")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Payment_Method_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("UserPaymentMethods");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Property<int>("Review_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Review_Id"));

                    b.Property<int>("Booking_Id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int?>("Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id1")
                        .HasColumnType("int");

                    b.HasKey("Review_Id");

                    b.HasIndex("Booking_Id")
                        .IsUnique();

                    b.HasIndex("Room_Id");

                    b.HasIndex("User_Id1");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.BoardingHouse", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("BoardingHouses")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Booking", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("Room_Id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("User_Id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.ChatConversation", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "Host")
                        .WithMany("HostConversations")
                        .HasForeignKey("Host_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.Room", "Room")
                        .WithMany("ChatConversations")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("ChatConversations")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.ChatConversation", "ChatConversation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatConversationConversation_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("chatMessages")
                        .HasForeignKey("User_Id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatConversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.CheckBooking", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Booking", "Booking")
                        .WithMany("CheckBookings")
                        .HasForeignKey("Booking_Id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.HouseImage", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.BoardingHouse", "BoardingHouse")
                        .WithMany("HouseImages")
                        .HasForeignKey("BoardingHouseHouse_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardingHouse");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("User_Id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("Booking_Id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.UserPaymentMethod", "UserPaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("UserPaymentMethodPayment_Method_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("UserPaymentMethod");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Report", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterUser_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Room", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.BoardingHouse", "BoardingHouse")
                        .WithMany("Rooms")
                        .HasForeignKey("House_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.User", "Owner")
                        .WithMany("Rooms")
                        .HasForeignKey("Owner_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardingHouse");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.RoomImage", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Room", "Room")
                        .WithMany("RoomImages")
                        .HasForeignKey("Room_Id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.RoomProperty", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Room", "Room")
                        .WithOne("RoomProperty")
                        .HasForeignKey("MyApi.Domain.Entities.RoomProperty", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserInfor", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithOne("UserInfor")
                        .HasForeignKey("MyApi.Domain.Entities.UserInfor", "User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserPaymentMethod", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("Review", "Booking_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.Room", null)
                        .WithMany("Reviews")
                        .HasForeignKey("Room_Id");

                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("User_Id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.BoardingHouse", b =>
                {
                    b.Navigation("HouseImages");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Booking", b =>
                {
                    b.Navigation("CheckBookings");

                    b.Navigation("Payments");

                    b.Navigation("Review")
                        .IsRequired();
                });

            modelBuilder.Entity("MyApi.Domain.Entities.ChatConversation", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ChatConversations");

                    b.Navigation("Reviews");

                    b.Navigation("RoomImages");

                    b.Navigation("RoomProperty")
                        .IsRequired();
                });

            modelBuilder.Entity("MyApi.Domain.Entities.User", b =>
                {
                    b.Navigation("BoardingHouses");

                    b.Navigation("Bookings");

                    b.Navigation("ChatConversations");

                    b.Navigation("HostConversations");

                    b.Navigation("Notifications");

                    b.Navigation("PaymentMethods");

                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");

                    b.Navigation("UserInfor")
                        .IsRequired();

                    b.Navigation("chatMessages");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserPaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
