// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Infrastructure.Data;

#nullable disable

namespace MyApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205060326_fix")]
    partial class fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApi.Domain.Entities.BoardingHouse", b =>
                {
                    b.Property<int>("House_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("House_Id"));

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Create_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Electric_Cost")
                        .HasColumnType("int");

                    b.Property<string>("House_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Is_Elevator")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("Water_Cost")
                        .HasColumnType("int");

                    b.HasKey("House_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("BoardingHouses", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Booking_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("Check_In_Date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Check_Out_Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Booking_Id");

                    b.HasIndex("Room_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.ChatConversation", b =>
                {
                    b.Property<int>("Conversation_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Conversation_Id"));

                    b.Property<int>("Host_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_Message_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Conversation_Id");

                    b.HasIndex("Host_Id");

                    b.HasIndex("Room_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("ChatConversations", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Message_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Message_Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Conversation_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Message_Id");

                    b.HasIndex("Conversation_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.CheckBooking", b =>
                {
                    b.Property<int>("Check_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Check_Id"));

                    b.Property<int>("Booking_Id")
                        .HasColumnType("int");

                    b.Property<string>("Check")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("CheckIn");

                    b.Property<DateTime>("Check_Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Image_Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Check_Id");

                    b.HasIndex("Booking_Id");

                    b.ToTable("CheckBookings", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.FavoriteHouse", b =>
                {
                    b.Property<int>("Favorite_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Favorite_Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("House_Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<int?>("Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Favorite_Id");

                    b.HasIndex("House_Id");

                    b.HasIndex("Room_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("FavoriteHouse", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.HouseImage", b =>
                {
                    b.Property<int>("House_Image_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("House_Image_Id"));

                    b.Property<int>("House_Id")
                        .HasColumnType("int");

                    b.Property<string>("Image_Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Uploaded_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("House_Image_Id");

                    b.HasIndex("House_Id");

                    b.ToTable("HouseImage", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Notification_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Notification_Id"));

                    b.Property<DateTime>("Create_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("Is_Read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Notification_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_Id"));

                    b.Property<int>("Booking_Id")
                        .HasColumnType("int");

                    b.Property<long>("Deposit")
                        .HasColumnType("bigint");

                    b.Property<int>("Method_Paid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Paid_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Transaction_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Payment_Id");

                    b.HasIndex("Booking_Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Report_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Report_Id"));

                    b.Property<DateTime>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Reported_Id")
                        .HasColumnType("int");

                    b.Property<int>("Reporter_Id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Report_Id");

                    b.HasIndex("Reporter_Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Room_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Room_Id"));

                    b.Property<DateOnly?>("Check_In_Default")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("House_Id")
                        .HasColumnType("int");

                    b.Property<int>("Owner_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Room_Id");

                    b.HasIndex("House_Id");

                    b.HasIndex("Owner_Id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.RoomImage", b =>
                {
                    b.Property<int>("Image_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Image_Id"));

                    b.Property<string>("Image_Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Uploaded_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Image_Id");

                    b.HasIndex("Room_Id");

                    b.ToTable("RoomImages", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.RoomProperty", b =>
                {
                    b.Property<int>("Property_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Property_Id"));

                    b.Property<int>("Bed_Count")
                        .HasColumnType("int");

                    b.Property<bool>("Has_AirConditioner")
                        .HasColumnType("bit");

                    b.Property<bool>("Has_Closet")
                        .HasColumnType("bit");

                    b.Property<bool>("Has_Fridge")
                        .HasColumnType("bit");

                    b.Property<bool>("Has_Hot_Water")
                        .HasColumnType("bit");

                    b.Property<bool>("Has_Mezzanine")
                        .HasColumnType("bit");

                    b.Property<bool>("Has_Pet")
                        .HasColumnType("bit");

                    b.Property<bool>("Has_Wifi")
                        .HasColumnType("bit");

                    b.Property<bool>("Has_Window")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Property_Id");

                    b.HasIndex("Room_Id")
                        .IsUnique();

                    b.ToTable("RoomProperties");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<DateTime?>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Lock_Until")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("User_Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserInfor", b =>
                {
                    b.Property<int>("Infor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Infor_Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Update_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Infor_Id");

                    b.HasIndex("User_Id")
                        .IsUnique();

                    b.ToTable("UserInfor", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserPaymentMethod", b =>
                {
                    b.Property<int>("Payment_Method_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_Method_Id"));

                    b.Property<string>("Account_User_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bank_Account_Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bank_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Create_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Payment_Method_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("UserPaymentMethods", (string)null);
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Property<int>("Review_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Review_Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint")
                        .HasComment("Giá trị từ 1 đến 5");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Review_Id");

                    b.HasIndex("Room_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.BoardingHouse", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("BoardingHouses")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Booking", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.ChatConversation", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "Host")
                        .WithMany("HostConversations")
                        .HasForeignKey("Host_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.Room", "Room")
                        .WithMany("ChatConversations")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("ChatConversations")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Host");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.ChatConversation", "ChatConversation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("Conversation_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("chatMessages")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChatConversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.CheckBooking", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Booking", "Booking")
                        .WithMany("CheckBookings")
                        .HasForeignKey("Booking_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.FavoriteHouse", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.BoardingHouse", "BoardingHouse")
                        .WithMany("FavoriteHouses")
                        .HasForeignKey("House_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.Room", "Room")
                        .WithMany("FavoriteHouse")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("FavoriteHouses")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardingHouse");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.HouseImage", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.BoardingHouse", "BoardingHouse")
                        .WithMany("HouseImages")
                        .HasForeignKey("House_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoardingHouse");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("Booking_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Report", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("Reporter_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Room", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.BoardingHouse", "BoardingHouse")
                        .WithMany("Rooms")
                        .HasForeignKey("House_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.User", "Owner")
                        .WithMany("Rooms")
                        .HasForeignKey("Owner_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BoardingHouse");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.RoomImage", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Room", "Room")
                        .WithMany("RoomImages")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.RoomProperty", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Room", "Room")
                        .WithOne("RoomProperty")
                        .HasForeignKey("MyApi.Domain.Entities.RoomProperty", "Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserInfor", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithOne("UserInfor")
                        .HasForeignKey("MyApi.Domain.Entities.UserInfor", "User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserPaymentMethod", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.HasOne("MyApi.Domain.Entities.Room", "Room")
                        .WithMany("Reviews")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.BoardingHouse", b =>
                {
                    b.Navigation("FavoriteHouses");

                    b.Navigation("HouseImages");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Booking", b =>
                {
                    b.Navigation("CheckBookings");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.ChatConversation", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("MyApi.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ChatConversations");

                    b.Navigation("FavoriteHouse");

                    b.Navigation("Reviews");

                    b.Navigation("RoomImages");

                    b.Navigation("RoomProperty")
                        .IsRequired();
                });

            modelBuilder.Entity("MyApi.Domain.Entities.User", b =>
                {
                    b.Navigation("BoardingHouses");

                    b.Navigation("Bookings");

                    b.Navigation("ChatConversations");

                    b.Navigation("FavoriteHouses");

                    b.Navigation("HostConversations");

                    b.Navigation("Notifications");

                    b.Navigation("PaymentMethods");

                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");

                    b.Navigation("UserInfor")
                        .IsRequired();

                    b.Navigation("chatMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
